name: 'PBuild'
description: 'Package or Project build'
author: 'Your Name'

inputs:
  dist:
    description: 'The distribution target for pbuild'
    required: false
    default: 'tumbleweed'
  working-directory:
    description: 'The directory where the dist folder is located'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Add openSUSE Tools repository and install build package
      shell: bash
      run: |
        curl -fsSL https://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_Next/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/openSUSE_Tools.gpg > /dev/null
        echo 'deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_Next/ /' | sudo tee /etc/apt/sources.list.d/openSUSE_Tools.list
        sudo apt-get update
        sudo apt-get install -y build
        # to be moved to build package
        sudo apt-get install -y libwww-perl libxml-parser-perl

    - name: Run pbuild
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        [ -e "_manifest" -o -e "_pbuild" ] || ORPHAN=--orphan
        pbuild --dist=${{ inputs.dist }} $ORPHAN --vm-type=docker
